version: "2"

services:
  origami-api:
    build: .
    ports:
      - 5000:5000
    volumes:
      - ./server.js:/usr/src/app/server.js
    environment:
      origami_mailgun_api_key: foo
      origami_mailgun_domain: bar
      origami_jwt_secret: secret
      origami_dbuser: admin
      origami_dbuserpass: admin
      origami_database: origami-api
      origami_dbhost: db
    depends_on:
      - db

  db:
    build:
      context: ./origami-mongo
    volumes:
      - ./mongo-data:/data/db
    environment:
      origami_database: origami-api
      origami_dbuser: admin
      origami_dbuserpass: admin
    command: --auth --storageEngine wiredTiger